apiVersion: v1
kind: ConfigMap
metadata:
  name: disable-sc-sh
data:
  disable-sc.sh: |
    KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    storageClass='default'
    apk update -q
    apk add -q curl

    # Get
    curl -X GET --header "Authorization: Bearer $KUBE_TOKEN" --insecure https://kubernetes.default/apis/storage.k8s.io/v1/storageclasses/${storageClass}

    # Patch
    curl --request PATCH \
    -H "Authorization: Bearer $KUBE_TOKEN" \
    -H "Content-Type: application/merge-patch+json" \
    --insecure https://kubernetes.default/apis/storage.k8s.io/v1/storageclasses/${storageClass} \
    -d '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
