apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: disable-sc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sc-role
subjects:
- kind: ServiceAccount
  name: disable-sc
  namespace: default
