---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      version: "6.31.x"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm-charts
        namespace: flux-system
      interval: 60m
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        # loki datasource: http://loki-gateway/
        - name: Loki
          type: loki
          url: http://loki-gateway/
          access: proxy
          isDefault: false
          uid: loki
          jsonData:
            derivedFields:
            - datasourceUid: tempo
              matcherRegex: ((\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+))
              url: '$${__value.raw}'
              name: TraceID
        # Prometheus datasource: http://kube-prometheus-stack-prometheus:9090
        - name: prometheus
          type: prometheus
          url: http://kube-prometheus-stack-prometheus:9090
          access: proxy
          isDefault: true
