apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ceph
  namespace: flux-system
spec:
  interval: 3m0s
  dependsOn:
    - name: infra-sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/ceph
  prune: true
  wait: true
  timeout: 10m0s
  healthChecks:
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      name: ceph-block
      namespace: rook-ceph
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      name: ceph-bucket
      namespace: rook-ceph
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      name: ceph-filesystem
      namespace: rook-ceph
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-osd-0
      namespace: rook-ceph
