apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 3m0s
  dependsOn:
    - name: ceph
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring/kube-prometheus-stack
  prune: true
  wait: true
  timeout: 10m0s
