apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki-simple-scalable
  namespace: flux-system
spec:
  interval: 3m0s
  dependsOn:
    - name: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring/loki-simple-scalable
  prune: true
  wait: true
  timeout: 10m0s
