apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: 1.9.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    toolbox:
      enabled: true
    csi:
      provisionerTolerations:
        - effect: NoSchedule
          key: storage-node
          operator: Exists
      pluginTolerations:
        - effect: NoSchedule
          key: storage-node
          operator: Exists
