apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: v1.7.2
    operatorNamespace: rook-ceph
    # Needed for AKS running
    csi:
      provisionerTolerations:
        - effect: NoSchedule
          key: storage-node
          operator: Exists
      pluginTolerations:
        - effect: NoSchedule
          key: storage-node
          operator: Exists
    agent:
      # AKS: https://rook.github.io/docs/rook/v1.7/flexvolume.html#azure-aks
      flexVolumeDirPath: "/etc/kubernetes/volumeplugins"
