---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "3.11.x"
      sourceRef:
        kind: HelmRepository
        name: grafana-helm-charts
        namespace: flux-system
      interval: 60m
  values:
    initContainer:
      enabled: true
      fsInotifyMaxUserInstances: 512

    serviceMonitor:
      enabled: true

    config:
      lokiAddress: http://loki-gateway/loki/api/v1/push
